<?php
ob_start();
/**
 * The form
 *
 * Validation and generation
 */
if(isset($_POST['submit']) && $_POST['submit'] === 'Publish'){
    $this->model = new \Models\Model();
    if(isset($_POST['delete']) && !empty($_POST['delete'])){
        $this->model->deleteTag();
    }
    if(isset($_POST['update']) && isset($_POST['updateTo']) && !empty($_POST['update']) && !empty($_POST['updateTo'])){
        $this->model->updateTag();
    }
    if(isset($_POST['tag']) && !empty($_POST['tag'])){
        $this->model->insertTag();
    }
    ob_end_clean();
}
?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 id="h1"><a href="index.php?action=adminPanel">Back Home</a></h1><hr />
            <div id="content">
                <h4>
                    <?php
                    $this->model = new \Forms\manageTagsForm(new \Models\Model());
                    /**
                     * the form itself autogenerated
                     */

                    echo "<h3>The tag which you selected was: <u>" . $_POST['delete'] . "</u></h3><hr>";
                    ?>
                    <?php echo $this->model->getStartTag()?>
                    <?php foreach($this->model->fields as $field) : ?>
                        <?php echo  $field->getLabelTag();?>
                        <?php
                        $array = $field->getInput();
                        if(is_array($array)){
                            foreach ($array as $item){
                                echo $item;
                            }
                        }else{
                            echo $field->getInput();}?>
                    <?php endforeach ?>
                    <?php
                    
                    ?>
                    <hr>
                </h4>
            </div>
        </div>
    </div>
</div>
</body>
