<html>
<body>
<div class="container">
    <div class="jumbotron">
        <h1>My Blog</h1>
        <div id="header_div">
            <a href="index.php?action=login"> <?php
                if(session_start() && isset($_SESSION['username'])){
                    echo $_SESSION['username'] . '   Logout';
                }else{
                    header("Location: index.php?action=login ");
                }
                ?></a>
        </div>
    </div>
</div>
<?php
ob_start();
/**
 * The form
 *
 * Validation and generation
 */
if(isset($_POST['submit']) && $_POST['submit'] === 'Publish'){
    $this->model = new \Models\Model();
    if(isset($_POST['delete']) && !empty($_POST['delete'])){
        $this->model->deleteTag();
    }
    if(isset($_POST['update']) && isset($_POST['updateTo']) && !empty($_POST['update']) && !empty($_POST['updateTo'])){
        $this->model->updateTag();
    }
    if(isset($_POST['tag']) && !empty($_POST['tag'])){
        $this->model->insertTag();
    }
    ob_end_clean();
}
?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 id="h1"><a href="index.php?action=adminPanel">Back Home</a></h1><hr />
            <div id="content">
                <h4>
                    <?php
                    $this->model = new \Forms\manageTagsForm(new \Models\Model());
                    /**
                     * the form itself autogenerated
                     */
                    ?>
                    <?php echo $this->model->getStartTag()?>
                    <?php foreach($this->model->fields as $field) : ?>
                        <?php echo '<hr />' . $field->getLabelTag();?>
                        <?php
                        $array = $field->getInput();
                        if(is_array($array)){
                            foreach ($array as $item){
                                echo $item;
                            }
                        }else{
                            echo $field->getInput();}?>
                    <?php endforeach ?>
                </h4>
            </div>
        </div>
    </div>
</div>
</body>
